version: "3.9"

services:
  db:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
  go-app:
    build: ./go-app
    ports:
      - 8080:8080
    depends_on:
      - db
    